
os: linux
arch:
 - amd64
 - ppc64le
language: cpp
sudo: false
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: mkdir build && cd build && cmake ../ && make && ./bin/citygmltest ../data/berlin_open_data_sample_data.citygml && ./bin/citygmltest ../data/b1_lod2_s.gml && ./bin/citygmltest ../data/FZK-Haus-LoD0-KIT-IAI-KHH-B36-V1.gml 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - libxerces-c-dev
      - libxerces-c3.1
      - libgdal1i
      - libgdal-dev
      - cmake-data
      - cmake
      - g++-4.8
      - gcc-4.8
      - libopenscenegraph-dev
